version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    command: start-dev
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - postgres
    ports:
      - 9080:8080
    networks:
      - keycloak-network
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./database.dev.env
    ports:
      - 5432:5432
    networks:
      - keycloak-network
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - ./database.dev.env
    ports:
      - '5050:80'

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
